version: '3.8'

services:
    postgres:
        image: postgres:latest
        restart: always
        env_file:
            - '.env'
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - '${POSTGRES_PORT}:5432'
        volumes:
            - pgdata:/var/lib/postgresql/data
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    redis:
        image: redis:latest
        restart: always
        ports:
            - '${REDIS_PORT}:6379'

    nestjs_app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '${APP_PORT}:3000'
        depends_on:
            - postgres
            - redis

volumes:
    pgdata:
